Update Jenkinsfile

diff --git a/CI-CD/spring-boot-app/src-main/Jenkinsfile b/CI-CD/spring-boot-app/src-main/Jenkinsfile
--- a/CI-CD/spring-boot-app/src-main/Jenkinsfile
+++ b/CI-CD/spring-boot-app/src-main/Jenkinsfile
@@ -1,84 +1,40 @@
 pipeline {
-    agent {
-        docker {
-            image 'cicd-pipeline:v1'
-            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
-        }
-    }
-
-    environment {
-        SONAR_URL = "http://localhost:9000"
-        DOCKER_IMAGE = "teju96/spring-boot-demo:${BUILD_NUMBER}"
-    }
+    agent any
 
     stages {
 
         stage('Checkout') {
             steps {
-                git branch: 'main',
-                url: 'https://github.com/Tejashwini-Javejar/orn-ai-devops-assessment.git'
+                checkout scm
             }
         }
 
         stage('Build Maven') {
             steps {
-                dir('spring-boot-app') {
-                    sh 'mvn clean package -DskipTests'
-                }
-            }
-        }
-
-        stage('Verify Artifact') {
-            steps {
-                dir('spring-boot-app') {
-                    sh 'ls -lh target/'
-                }
-            }
-        }
-
-        stage('SonarQube Analysis') {
-            steps {
-                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
-                    dir('spring-boot-app') {
-                        sh '''
-                        mvn sonar:sonar \
-                          -Dsonar.host.url=$SONAR_URL \
-                          -Dsonar.login=$SONAR_AUTH_TOKEN
-                        '''
-                    }
-                }
+                sh 'mvn clean package -DskipTests'
             }
         }
 
         stage('Build Docker Image') {
             steps {
-                dir('spring-boot-app') {
-                    sh 'docker build -t $DOCKER_IMAGE .'
-                }
+                sh 'docker build -t cicd-pipeline:v1 .'
             }
         }
 
-        stage('Push Docker Image') {
+        stage('Run Container') {
             steps {
-                withCredentials([usernamePassword(credentialsId: 'docker-cred',
-                    usernameVariable: 'USER',
-                    passwordVariable: 'PASS')]) {
-
-                    sh '''
-                    echo $PASS | docker login -u $USER --password-stdin
-                    docker push $DOCKER_IMAGE
-                    '''
-                }
+                sh 'docker rm -f app || true'
+                sh 'docker run -d --name app -p 8080:8080 cicd-pipeline:v1'
             }
         }
     }
 
     post {
         success {
-            echo "🚀 CI/CD Pipeline SUCCESS"
+            echo '✅ Pipeline SUCCESS'
         }
         failure {
-            echo "❌ Pipeline FAILED"
+            echo '❌ Pipeline FAILED'
         }
     }
 }
