Update Jenkinsfile

diff --git a/Capstone-Project/Jenkins/Jenkinsfile b/Capstone-Project/Jenkins/Jenkinsfile
--- a/Capstone-Project/Jenkins/Jenkinsfile
+++ b/Capstone-Project/Jenkins/Jenkinsfile
@@ -9,8 +9,10 @@ pipeline {
 
 
     environment {
+
         IMAGE_NAME = "teju96/capstone-project"
         IMAGE_TAG = "${BUILD_NUMBER}"
+
     }
 
 
@@ -18,98 +20,188 @@ pipeline {
 
 
         stage('Checkout') {
+
             steps {
+
                 checkout scm
+
             }
+
         }
 
 
         stage('Install Dependencies') {
+
             steps {
+
                 dir('Capstone Project/app') {
+
                     sh '''
                     pip install -r requirements.txt
                     '''
+
                 }
+
             }
+
         }
 
 
         stage('SonarQube Scan') {
+
             steps {
+
                 withSonarQubeEnv('SonarQube') {
+
                     sh '''
                     sonar-scanner \
                     -Dsonar.projectKey=capstone-project \
                     -Dsonar.sources="Capstone Project/app" \
                     -Dsonar.python.version=3.14
                     '''
+
                 }
+
             }
+
         }
 
 
         stage('Build Docker Image') {
+
             steps {
+
                 dir('Capstone Project/app') {
+
                     sh '''
                     docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                     '''
+
                 }
+
             }
+
         }
 
 
         stage('Push Docker Image') {
+
             steps {
 
-                withCredentials([usernamePassword(
-                    credentialsId: 'docker-cred',
-                    usernameVariable: 'USERNAME',
-                    passwordVariable: 'PASSWORD'
-                )]) {
+                withCredentials([
+                    usernamePassword(
+                        credentialsId: 'docker-cred',
+                        usernameVariable: 'DOCKER_USERNAME',
+                        passwordVariable: 'DOCKER_PASSWORD'
+                    )
+                ]) {
+
 
                     sh '''
-                    echo $PASSWORD | docker login -u $USERNAME --password-stdin
+                    echo $DOCKER_PASSWORD | docker login \
+                    -u $DOCKER_USERNAME \
+                    --password-stdin
+
 
                     docker push ${IMAGE_NAME}:${IMAGE_TAG}
 
+
                     docker logout
                     '''
+
                 }
+
             }
+
         }
 
 
-        stage('Update Deployment') {
+
+        stage('Update Kubernetes Deployment') {
+
             steps {
-                sh '''
-                sed -i "s|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|" "Capstone Project/K8s/deployment.yaml"
 
-                echo "Updated deployment file:"
+                sh '''
+
+                sed -i "s|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|" \
+                "Capstone Project/K8s/deployment.yaml"
+
+
+                echo "Updated deployment.yaml:"
                 cat "Capstone Project/K8s/deployment.yaml"
+
                 '''
+
             }
+
         }
+
+
+
+        stage('Commit and Push Kubernetes Manifest') {
+
+            steps {
+
+
+                withCredentials([
+                    usernamePassword(
+                        credentialsId: 'github-cred',
+                        usernameVariable: 'GITHUB_USERNAME',
+                        passwordVariable: 'GITHUB_TOKEN'
+                    )
+                ]) {
+
+
+                    sh '''
+
+                    git config user.email "jenkins@localhost"
+
+                    git config user.name "Jenkins"
+
+
+                    git add "Capstone Project/K8s/deployment.yaml"
+
+
+                    git commit -m "Update image tag to ${IMAGE_TAG}" || true
+
+
+                    git push https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/Tejashwini-Javejar/orn-ai-devops-assessment.git main
+
+                    '''
+
+                }
+
+            }
+
+        }
+
 
     }
 
 
     post {
 
+
         success {
-            echo "Pipeline completed successfully!"
+
+            echo "✅ Pipeline completed successfully!"
+
         }
 
 
         failure {
-            echo "Pipeline failed! Please check logs."
+
+            echo "❌ Pipeline failed! Check Jenkins logs."
+
         }
 
 
         always {
+
             cleanWs()
+
         }
+
 
     }
 
